export const INTERESTS: ReadonlyArray<{ slug: string; name: string }> = [
  { slug: 'afrobeats', name: 'Afrobeats' },
  { slug: 'amapiano', name: 'Amapiano' },
  { slug: 'hip-hop', name: 'Hip-Hop' },
  { slug: 'afro-house', name: 'Afro House' },
  { slug: 'alte', name: 'Alté' },
  { slug: 'rb-soul', name: 'R&B & Soul' },
  { slug: 'gospel', name: 'Gospel' },
  { slug: 'live-music', name: 'Live Music' },
  { slug: 'dj-sets', name: 'DJ Sets' },
  { slug: 'concerts', name: 'Concerts' },
  { slug: 'festivals', name: 'Festivals' },
  { slug: 'parties', name: 'Parties' },
  { slug: 'day-parties', name: 'Day Parties' },
  { slug: 'club-nights', name: 'Club Nights' },
  { slug: 'brunch', name: 'Brunch' },
  { slug: 'food-drink', name: 'Food & Drink' },
  { slug: 'comedy', name: 'Comedy' },
  { slug: 'theatre', name: 'Theatre' },
  { slug: 'art-exhibitions', name: 'Art & Exhibitions' },
  { slug: 'fashion', name: 'Fashion' },
  { slug: 'film-screenings', name: 'Film & Screenings' },
  { slug: 'sports', name: 'Sports' },
  { slug: 'gaming-esports', name: 'Gaming & Esports' },
  { slug: 'tech-networking', name: 'Tech & Networking' },
  { slug: 'wellness', name: 'Wellness' },
  { slug: 'fitness', name: 'Fitness' },
  { slug: 'outdoors', name: 'Outdoors' },
  { slug: 'karaoke', name: 'Karaoke' },
  { slug: 'spoken-word', name: 'Spoken Word' },
  { slug: 'cultural-heritage', name: 'Cultural & Heritage' },
];
