import { Injectable } from '@nestjs/common';
import { stringify } from 'csv-stringify/sync';
import * as ExcelJS from 'exceljs';
import {
  ExportColumn,
  ExportDefinition,
  ExportFormat,
  RenderedExport,
} from './export-definition';

const BRAND_COLOR = 'FF111111';
const BRAND_ACCENT = 'FFF4F4F5';

/** One export definition in, branded CSV / XLSX / PDF out. */
@Injectable()
export class ExportEngineService {
  async render<T>(
    definition: ExportDefinition<T>,
    format: ExportFormat,
  ): Promise<RenderedExport> {
    switch (format) {
      case 'csv':
        return this.csv(definition);
      case 'xlsx':
        return this.xlsx(definition);
      case 'pdf':
        return this.pdf(definition);
    }
  }

  private cell<T>(column: ExportColumn<T>, row: T): string | number {
    const raw = column.value(row);

    if (raw === null) {
      return '';
    }

    if (column.format === 'money' && typeof raw === 'number') {
      return (raw / 100).toFixed(2);
    }

    return raw;
  }

  private async csv<T>(
    definition: ExportDefinition<T>,
  ): Promise<RenderedExport> {
    const records: Array<Array<string | number>> = [
      definition.columns.map((column) => column.header),
    ];

    for await (const row of definition.rows) {
      records.push(definition.columns.map((column) => this.cell(column, row)));
    }

    return {
      filename: `${definition.filename}.csv`,
      contentType: 'text/csv; charset=utf-8',
      body: Buffer.from('\ufeff' + stringify(records)),
    };
  }

  private async xlsx<T>(
    definition: ExportDefinition<T>,
  ): Promise<RenderedExport> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'cheevo';

    const sheet = workbook.addWorksheet(definition.title.slice(0, 31), {
      views: [{ state: 'frozen', ySplit: 3 }],
    });

    sheet.mergeCells(1, 1, 1, definition.columns.length);
    const titleCell = sheet.getCell(1, 1);
    titleCell.value = definition.title;
    titleCell.font = { bold: true, size: 14 };

    sheet.mergeCells(2, 1, 2, definition.columns.length);
    const subtitleCell = sheet.getCell(2, 1);
    subtitleCell.value =
      definition.subtitle ??
      `Generated by cheevo \u00b7 ${new Date().toISOString().slice(0, 10)}`;
    subtitleCell.font = { size: 10, color: { argb: 'FF71717A' } };

    const headerRow = sheet.getRow(3);

    definition.columns.forEach((column, index) => {
      const cell = headerRow.getCell(index + 1);
      cell.value = column.header;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: BRAND_COLOR },
      };
      sheet.getColumn(index + 1).width = Math.max(14, column.header.length + 4);
    });

    let rowIndex = 4;

    for await (const row of definition.rows) {
      const sheetRow = sheet.getRow(rowIndex);

      definition.columns.forEach((column, index) => {
        const cell = sheetRow.getCell(index + 1);
        const raw = column.value(row);

        if (column.format === 'money' && typeof raw === 'number') {
          cell.value = raw / 100;
          cell.numFmt = '#,##0.00';
        } else {
          cell.value = raw ?? '';
        }
      });

      if (rowIndex % 2 === 0) {
        for (let i = 1; i <= definition.columns.length; i += 1) {
          sheetRow.getCell(i).fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: BRAND_ACCENT },
          };
        }
      }

      rowIndex += 1;
    }

    const buffer = await workbook.xlsx.writeBuffer();

    return {
      filename: `${definition.filename}.xlsx`,
      contentType:
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      body: Buffer.from(buffer),
    };
  }

  private async pdf<T>(
    definition: ExportDefinition<T>,
  ): Promise<RenderedExport> {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const pdfmake = require('pdfmake') as {
      setFonts: (fonts: Record<string, Record<string, string>>) => void;
      setUrlAccessPolicy: (cb: (url: string) => boolean) => void;
      setLocalAccessPolicy: (cb: (path: string) => boolean) => void;
      createPdf: (def: unknown) => { getBuffer: () => Promise<Buffer> };
    };

    pdfmake.setFonts({
      Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique',
      },
    });
    pdfmake.setUrlAccessPolicy(() => false);
    // pdfkit resolves the PDF standard-14 fonts by name — no other "file" may load.
    pdfmake.setLocalAccessPolicy((path) =>
      [
        'Helvetica',
        'Helvetica-Bold',
        'Helvetica-Oblique',
        'Helvetica-BoldOblique',
      ].includes(path),
    );

    const body: Array<Array<Record<string, unknown>>> = [
      definition.columns.map((column) => ({
        text: column.header,
        style: 'tableHeader',
      })),
    ];

    for await (const row of definition.rows) {
      body.push(
        definition.columns.map((column) => {
          const raw = column.value(row);

          if (column.format === 'money' && typeof raw === 'number') {
            return {
              text: (raw / 100).toLocaleString('en-NG', {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2,
              }),
              alignment: 'right',
            };
          }

          return { text: raw === null ? '' : String(raw) };
        }),
      );
    }

    const generated = `Generated by cheevo \u00b7 ${new Date().toISOString().slice(0, 10)}`;

    const docDefinition = {
      pageOrientation: definition.columns.length > 6 ? 'landscape' : 'portrait',
      pageMargins: [32, 56, 32, 48],
      header: {
        columns: [{ text: 'cheevo', style: 'brand', margin: [32, 20, 0, 0] }],
      },
      footer: (currentPage: number, pageCount: number) => ({
        columns: [
          { text: generated, style: 'footer', margin: [32, 0, 0, 0] },
          {
            text: `${currentPage} / ${pageCount}`,
            alignment: 'right',
            style: 'footer',
            margin: [0, 0, 32, 0],
          },
        ],
      }),
      content: [
        { text: definition.title, style: 'title' },
        ...(definition.subtitle
          ? [{ text: definition.subtitle, style: 'subtitle' }]
          : []),
        {
          table: {
            headerRows: 1,
            widths: definition.columns.map(() => '*'),
            body,
          },
          layout: {
            fillColor: (rowIndex: number) =>
              rowIndex === 0
                ? '#111111'
                : rowIndex % 2 === 0
                  ? '#f4f4f5'
                  : null,
            hLineWidth: () => 0,
            vLineWidth: () => 0,
            paddingTop: () => 6,
            paddingBottom: () => 6,
            paddingLeft: () => 8,
            paddingRight: () => 8,
          },
          margin: [0, 12, 0, 0],
        },
      ],
      styles: {
        brand: { fontSize: 14, bold: true },
        title: { fontSize: 16, bold: true },
        subtitle: { fontSize: 9, color: '#71717a', margin: [0, 4, 0, 0] },
        tableHeader: { color: '#ffffff', bold: true, fontSize: 9 },
        footer: { fontSize: 8, color: '#a1a1aa' },
      },
      defaultStyle: { font: 'Helvetica', fontSize: 9 },
    };

    const buffer = await pdfmake.createPdf(docDefinition).getBuffer();

    return {
      filename: `${definition.filename}.pdf`,
      contentType: 'application/pdf',
      body: Buffer.from(buffer),
    };
  }
}
